import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Daniel',
      email: 'daniel3levi@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Testa',
      email: 'test@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'פלייר פטנט 7 אינץ',
      slug: 'tools-pliers-locking_pliers',
      category: 'פליירים',
      image: 'images/p1.jpg',
      price: 39,
      countInStock: 2,
      brand: 'Tecno Sharon',
      rating: 4.5,
      numReviews: 10,
      description: 'פלייר פטנט 7" מקצועי',
    },
    {
      name: 'פטיש 2 ק״ג',
      slug: 'tools-hammers',
      category: 'פטישים',
      image: 'images/p2.jpg',
      price: 22,
      countInStock: 4,
      brand: 'Tecno Sharon',
      rating: 4,
      numReviews: 6,
      description: 'פטיש 2000 גרם (2 ק"ג) ידית עץ',
    },
    {
      name: 'מנורות חסכוניות',
      slug: 'lighting-economical_lamps',
      category: 'תאורה',
      image: 'images/p3.jpg',
      price: 46,
      countInStock: 5,
      brand: 'Sun-Light',
      rating: 5,
      numReviews: 3,
      description: 'מנורות חסכוניות 30W אור-חם',
    },
    {
      name: 'סופרקריל מט 5 ליטר',
      slug: 'paint-water-wall_paint',
      category: 'צבעים',
      image: 'images/p4.jpg',
      price: 168,
      countInStock: 0,
      brand: 'טמבור',
      rating: 1,
      numReviews: 8,
      description:
        'צבע אקרילי איכותי על בסיס מים בגימור מט, מעניק חזות יפה בשילוב עמידות גבוהה במיוחד לאורך זמן. כיסוי גבוה במיוחד, ייבוש מהיר, צבע נושם ללא עופרת וכרומטיים. עומד בתקן ישראלי 1945 ובעל תו ירוק. לשימוש פנימי וחיצוני.',
    },
    {
      name: 'נורת פחם אגס צורת E27 60W ',
      slug: 'lighting-charcoal_lamps',
      category: 'תאורה',
      image: 'images/p5.jpg',
      price: 25,
      countInStock: 0,
      brand: 'ניסקו',
      rating: 2,
      numReviews: 15,
      description:
        'נורת פחם 60W בצורת אגס יכולה לשמש כתאורה דקורטיבית יוצאת דופן בעזרת חוט הלהט המעוצב שלה. מתאימה לבתי מגורים ובמיוחד למלונות, מסעדות וברים.',
    },
    {
      name: 'פטיש גומי רצפים לבן 225 גרם ',
      slug: 'tools-hammers_sequences',
      category: 'פטישים',
      image: 'images/p6.jpg',
      price: 25,
      countInStock: 21,
      brand: 'TOLSEN',
      rating: 4,
      numReviews: 5,
      description:
        'פטיש גומי רצפים לבן 225 גרם, ראש פטיש מגומי טבעי, ידית פיברגלס משקל ראש 225 גרם.',
    },
    {
      name: 'פלייר בידוד עבה 7״',
      slug: 'tools-pliers-insulation_pliers',
      category: 'פליירים',
      image: 'images/p7.jpg',
      price: 19,
      countInStock: 7,
      brand: 'PROXEN',
      rating: 3,
      numReviews: 2,
      description: 'פלייר בידוד עבה לכל מטרה',
    },
    {
      name: 'נורת ליבון לד E27 15W, אור חם',
      slug: 'lighting-led_lamps',
      category: 'תאורה',
      image: 'images/p8.jpg',
      price: 15,
      countInStock: 0,
      brand: 'ניסקו',
      rating: 2,
      numReviews: 22,
      description:
        '1500 לומן, נורת ליבון לד 15W היא התחליף לנורת ליבון מסורתית 100W – בעלת גוון ואיכות אורית הקרובה ביותר לנורות המקוריות. בעלת עוצמה אורית ייחודית וזווית הארה גדולה עם פיזור אור אחיד. אינה מיועדת לשימוש בגופים אטומים.',
    },
    {
      name: 'ורנית 2.5 ליטר ערמון טמבור',
      slug: 'paint-oil-wall_paint',
      category: 'צבעים',
      image: 'images/p9.jpg',
      price: 185,
      countInStock: 12,
      brand: 'טמבור',
      rating: 1,
      numReviews: 3,
      description:
        'לכה להגנה על עץ, מותאמת במיוחד לתנאי האקלים בארץ, לשימוש פנימי וחיצוני.',
    },
    {
      name: '0.75 ליטר פוליאור על בסיס מים מט',
      slug: 'paint-water-wall_paint_polyor',
      category: 'צבעים',
      image: 'images/p10.jpg',
      price: 74,
      countInStock: 6,
      brand: 'טמבור',
      rating: 2,
      numReviews: 4,
      description:
        'צבע סינתטי עליון על בסיס מים לעץ, מתכת וקירות חדשים וישנים. ללא ריח לוואי, מתאים לחדרי ילדים בעל תו תקן ירוק, ייבוש מהיר, קל לניקוי ובעל כושר השתפכות מלאה. בגימור משי. לשימוש פנימי וחיצוני.',
    },

    {
      name: 'סופרקריל מט פלוס 18 ליטר',
      slug: 'paint-water-wall_paint_math',
      category: 'צבעים',
      image: 'images/p11.jpg',
      price: 310,
      countInStock: 3,
      brand: 'טמבור',
      rating: 3,
      numReviews: 16,
      description:
        'סופרקריל מט פלוס מבית טמבור – צבע קיר אקרילי בגוון לבן ואיכותי על בסיס מים בגימור מט. ',
    },
    {
      name: 'קטר בידוד עבה',
      slug: 'tools-pliers-locomotive_pliers',
      category: 'פליירים',
      image: 'images/p12.jpg',
      price: 24,
      countInStock: 6,
      brand: 'Tecno-Sharon',
      rating: 1,
      numReviews: 12,
      description: 'קטר בידוד עבה לכל מטרה.',
    },
  ],
};

export default data;
